### ISSUE TITLE
Element type of empty array?

### ISSUE THREAD

**Issue by eonist** [kostiakoval/Mirror#20]
With your mirror framework, is it possible to get the Element type of an empty array?  

let a:Array<String> = []

And then get String somehow?

**Comment by kostiakoval** [comment]
There was a lot of changes to Reflection API in Swift. The Mirror framework unfortunately haven't been updated. 
the element <T> of Array is required when you create it. Also you can use `is` or `as` operator to check what types  are stored in array 

``` swift
let a: Array<Int> = []
if a is [Int] {
    print(" It's [Int]")
}
```

I hope this could help you

**Comment by eonist** [comment]
Thanks for your swift reply, pun intended. 

Yes, you can derive the array element type if the array is assigned to a variable. But my efforts with swift Mirror doesnt allow this. You can derive the element type of an empty array by doing Array<Int>().dynamicType.Element().dynamicType// Int. But if you use Mirror this just doesn't work. 

I guess my question is, can your Mirror framework extract array Element type for empty arrays.

Side note: attemting to make a class that can store classes in an xml doc

**Comment by eonist** [comment]
Anyways, I know you are very busy. Ive tested everything i can think of. And what it came down to is that the type that Mirror returns isn't useable as say a generic type in swift. So the only viable option was to keep reflecting variables if they were of type of type: Array. And use Regular Expression to extract the array type if the array was empty.
