### ISSUE TITLE
typesShortName is sth wrong

### ISSUE THREAD

**Issue by CharlinFeng** [kostiakoval/Mirror#3]
if my class has any optional properties,your typesShortName is not work well:

such as:

```
class Person{
    var name: String?
    var age: Int?
    var dog: Dog?
    var dogs: [Dog]?
}

class Dog {
}
```

then,i use Mirror，

```
let p1 = Person()
let mirror = Mirror(p1)
println(mirror.typesShortName)
```

print msg like this:

[String>, Int>, Dog>, Dog>>]

i want,the result is like this:

[String, Int, Dog, [Dog]]

or

[String, Int, Dog, Array<Dog>]

oh, i need optional property, and optional Array<T> property，can you support it ?? thank you!!!

**Comment by kostiakoval** [comment]
I think it's because of optional type. The fulsome of types include Module name. It probably wrongly removes it.

**Comment by CharlinFeng** [comment]
yes,  i write a dictionary convert to model framework   based your framework

the url is: https://github.com/nsdictionary/CFRuntime 

thank you first of all,

but,i  ran into some trouble because of Mirror could not support optional type,

i think,use regix should Solve this problem

such as:

var stu:Student?
the type is Mirror.optional(“Student”),use regix, we can take out Student,

var stus: [Student]
use regix, we can take out Array < Student >
