### ISSUE TITLE
Expect more features 

### ISSUE THREAD

**Issue by CharlinFeng** [kostiakoval/Mirror#6]
You have realized the following functions，thanks：
mirror.isClass
mirror.isStruct

But we may need more good features, such as：
mirror.isArray
mirror.isOptional

**Comment by kostiakoval** [comment]
Thanks for feedback. Sadly I don't have time now to work on those features :(
Would love if you could add it and make pull request :)

**Comment by CharlinFeng** [comment]
oh,ok,I am very interested in you, and have it, I will complete a strong framework of  dictionary convert to model

**Comment by kostiakoval** [comment]
Hi @nsdictionary, Check out #7 PR, I've added some new features
I will release it soon

**Comment by kostiakoval** [comment]
Not there is way to check for `isArray`, `isOptional`
